[package]
name = "e310x"
version = "0.1.1"
repository = "https://github.com/dvc94ch/e310x"
authors = ["David Craven <david@craven.ch>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "With svd2rust generated peripherals for Freedom E310 MCU's."
keywords = ["riscv", "register", "peripheral"]
license = "ISC"

[dependencies]
bare-metal = "^0.1.1"
riscv = "^0.1.3"
vcell = "^0.1.0"

[dependencies.riscv-rt]
optional = true
version = "^0.1.2"

[features]
rt = ["riscv-rt"]